INSERT INTO Employee(USERNAME, PASSWORD, FIRST_NAME, LAST_NAME) VALUES('user1', '1234', 'Adam', 'Smith');
INSERT INTO Employee(USERNAME, PASSWORD, FIRST_NAME, LAST_NAME) VALUES('user2', '1234', 'John', 'Boya');
INSERT INTO Employee(USERNAME, PASSWORD, FIRST_NAME, LAST_NAME) VALUES('user3', '1234', 'David', 'Lee');